---
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

gitea_urls:
  api: https://git.hsn.dev/api/v1
  download: https://git.hsn.dev
  skip_tls_verify: false
builds:
  - env: ["CGO_ENABLED=0"]
    binary: webhook
    goos:
      - linux
    goarch:
      - amd64
      - arch64

kos:
  - repository: git.hsn.dev/jahanson/cert-manager-webhook-dnsimple
    id: cert-manager-webhook-dnsimple
    # Chainguard Static is the default base image.
    # cgr.dev/chainguard/static
    # base_image: alpine
    bare: true
    creation_time: "{{.CommitTimestamp}}"
    ko_data_creation_time: "{{.CommitTimestamp}}"
    platforms:
      - linux/amd64
      - linux/arm64
    tags:
      - latest
      - "{{.Tag}}"
    flags:
      - -trimpath
    ldflags:
      - -w
      - -extldflags "-static"
      - -X main.Version={{.Tag}}
