---
creation_rules:
  - path_regex: testdata/dnsimple/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Cert-Manager-Test
    age: >-
      age10z089ltez8yuerju86k6aqd9vrmecm5gyn6gxmj68em0ztnyj46sd9840z
