---
creation_rules:
  - path_regex: testdata/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    # Cert-Manager-Test
    age: >-
      age18kj3xhlvgjeg2awwku3r8d95w360uysu0w5ejghnp4kh8qmtge5qwa2vjp
