name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: docker
    container:
      image: ghcr.io/goreleaser/goreleaser:v2.1.0
    steps:
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: https://x-access-token:${ GITHUB_TOKEN }@git.hsn.dev/${{ GITHUB_REPOSITORY }}
        run: |
          echo "URL: ${{ env.REPO_URL }}"
          git clone --depth 0 ${{ env.REPO_URL }} ${{ github.workspace }}
          echo "Repository cloned!"
      - name: Run goreleaser
        run: |
          echo ${{ github.workspace }}
          goreleaser release
