name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: docker
    container:
      image: ghcr.io/goreleaser/goreleaser:v2.1.0
    steps:
      - run: |
          echo ${{ github.workspace }}
          goreleaser release