name: goreleaser

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: docker
    container:
      image: ghcr.io/goreleaser/goreleaser:v2.1.0
    steps:
      - name: Checkout
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_URL: https://x-access-token:${GITHUB_TOKEN}@git.hsn.dev/${{ github.repository }}:${{ env.GITHUB_REF_NAME }}
        run: |
          printenv
          mkdir -p ${{ github.workspace }}
          echo "URL: ${{ env.REPO_URL }}"
          git clone ${{ env.REPO_URL }} ${{ github.workspace }}
          echo "Repository cloned!"
      - name: Run goreleaser
        env:
          GITHUB_TOKEN: ""
          GITEA_TOKEN: ${{ secrets.GITEA_TOKEN }}
          KO_DOCKER_REPO: git.hsn.dev/${{ github.repository_owner }}/cert-manager-webhook-dnsimple

        run: |
          echo ${{ github.workspace }}
          goreleaser release